import 'booking_model.dart';

class BookingData {
  static final List<Map<String, String>> _bookingsMapData = [
    {
      'id': 'B45678787876',
      'title': 'ອະພາດເມັນ',
      'date': '10 ກໍລະກົດ 2025',
      'location': 'ນະຄອນຫຼວງ ວຽງຈັນ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ສຳເລັດ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B46768787876',
      'title': 'ຫ້ອງແຖວແຊຫ້ອງ',
      'date': '25 ມິຖຸນາ 2025',
      'location': 'ໄຊຍະບູລີ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ລໍຖ້າຢືນຢັນ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B456670976',
      'title': 'ເຮືອນ 2 ຊັ້ນ',
      'date': '15 ພຶດສະພາ 2025',
      'location': 'ເຊກອງ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ຍົກເລີກ',
      'type': 'ເຊົ່າ',
    },
    {
      'id': 'B4567887876',
      'title': 'ວີລ້າ ສະຫງວນ',
      'date': '5 ມິຖຸນາ 2025',
      'location': 'ຫຼວງພະບາງ',
      'image': 'assets/images/house.jpg',
      'price': '75,000',
      'status': 'ສຳເລັດ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B4567098876',
      'title': 'ໂຮງແຮມດີສະຫຼາດ',
      'date': '30 ພຶດສະພາ 2025',
      'location': 'ຈຳປາສັກ',
      'image': 'assets/images/house.jpg',
      'price': '60,000',
      'status': 'ລໍຖ້າຢືນຢັນ',
      'type': 'ເຊົ່າ',
    },
    {
      'id': 'B567787876',
      'title': 'ອະພາດເມັນ',
      'date': '10 ກໍລະກົດ 2025',
      'location': 'ນະຄອນຫຼວງ ວຽງຈັນ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ສຳເລັດ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B09876676',
      'title': 'ຫ້ອງແຖວແຊຫ້ອງ',
      'date': '25 ມິຖຸນາ 2025',
      'location': 'ໄຊຍະບູລີ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ລໍຖ້າຢືນຢັນ',
      'type': 'ເຊົ່າ',
    },
    {
      'id': 'B455678876576',
      'title': 'ເຮືອນ 2 ຊັ້ນ',
      'date': '15 ພຶດສະພາ 2025',
      'location': 'ເຊກອງ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ຍົກເລີກ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B4509876776',
      'title': 'ວີລ້າ ສະຫງວນ',
      'date': '5 ມິຖຸນາ 2025',
      'location': 'ຫຼວງພະບາງ',
      'image': 'assets/images/house.jpg',
      'price': '75,000',
      'status': 'ສຳເລັດ',
      'type': 'ເຊົ່າ',
    },
    {
      'id': 'B4567230966',
      'title': 'ໂຮງແຮມດີສະຫຼາດ',
      'date': '30 ພຶດສະພາ 2025',
      'location': 'ຈຳປາສັກ',
      'image': 'assets/images/house.jpg',
      'price': '60,000',
      'status': 'ລໍຖ້າຢືນຢັນ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B45679787876',
      'title': 'ອະພາດເມັນ',
      'date': '10 ກໍລະກົດ 2025',
      'location': 'ນະຄອນຫຼວງ ວຽງຈັນ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ສຳເລັດ',
      'type': 'ເຊົ່າ',
    },
    {
      'id': 'B49823456876',
      'title': 'ຫ້ອງແຖວແຊຫ້ອງ',
      'date': '25 ມິຖຸນາ 2025',
      'location': 'ໄຊຍະບູລີ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ລໍຖ້າຢືນຢັນ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B4556798787876',
      'title': 'ເຮືອນ 2 ຊັ້ນ',
      'date': '15 ພຶດສະພາ 2025',
      'location': 'ເຊກອງ',
      'image': 'assets/images/house.jpg',
      'price': '50,000',
      'status': 'ຍົກເລີກ',
      'type': 'ເຊົ່າ',
    },
    {
      'id': 'B45679873456',
      'title': 'ວີລ້າ ສະຫງວນ',
      'date': '5 ມິຖຸນາ 2025',
      'location': 'ຫຼວງພະບາງ',
      'image': 'assets/images/house.jpg',
      'price': '75,000',
      'status': 'ສຳເລັດ',
      'type': 'ຂາຍ',
    },
    {
      'id': 'B458765677876',
      'title': 'ໂຮງແຮມດີສະຫຼາດ',
      'date': '30 ພຶດສະພາ 2025',
      'location': 'ຈຳປາສັກ',
      'image': 'assets/images/house.jpg',
      'price': '60,000',
      'status': 'ລໍຖ້າຢືນຢັນ',
      'type': 'ເຊົ່າ',
    },
  ];

  static List<BookingModel> getAllBookings() {
    return _bookingsMapData
        .map((bookingMap) => BookingModel.fromMap(bookingMap))
        .toList();
  }

  static List<Map<String, String>> getAllBookingsAsMap() {
    return _bookingsMapData;
  }
}